languageCode = "ru"
languageName = "Русский"
languageDirection = "ltr"
weight = 1

title = "DarkPro1337"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "02.01.2006"

  mainSections = ["posts", "projects"]
  # description = "My awesome website"

[params.author]
  name = "Артем Черных"
  image = "img/author.jpg"
  bio = "24 года, C# Разработчик"
  links = [
    { email = "mailto:darkprothekun@gmail.com" },
    { telegram = "https://t.me/DarkPro1337" },
    { github = "https://github.com/DarkPro1337" },
    { x-twitter = "https://x.com/darkpro1337" },
    { instagram = "https://instagram.com/darkpro1337" },
    { steam = "https://steamcommunity.com/id/darkpro1337/" },
    { unsplash = "https://unsplash.com/@darkpro1337" },
    { linkedin = "https://linkedin.com/in/darkpro1337" },
  ]
